import Sidebar from "@/components/Sidebar";
import Head from "next/head";


export default function Home() {
  return (
    <div>
			<Head>
				<title>Whatsapp 2.0</title>
				<meta name='description' content='Generated by Henry Web Dev' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Sidebar />
		</div>
  )
}
